services:
    visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        ports:
            - "88:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
