services:

    core:
        image: justinlaureano/wmsa-core:latest
        command: sh -c "php-fpm"
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: on-failure
        healthcheck:
            test: [ "CMD", "nc", "-zv", "localhost", "9000" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            - APP_ENV=local
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_DATABASE=wms
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REVERB_APP_ID=${REVERB_APP_ID}
            - REVERB_APP_KEY=${REVERB_APP_KEY}
            - REVERB_APP_SECRET=${REVERB_APP_SECRET}
            - REVERB_HOST="web"
            - REVERB_PORT=80
            - REVERB_SCHEME=http
            - REVERB_SCALING_ENABLED=true
            - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
            - LDAP_LOGGING=true
            - LDAP_CONNECTION=default
            - LDAP_HOST=${LDAP_HOST}
            - LDAP_USERNAME=${LDAP_USERNAME}
            - LDAP_PASSWORD=${LDAP_PASSWORD}
            - LDAP_PORT=${LDAP_PORT}
            - LDAP_BASE_DN=${LDAP_BASE_DN}
            - LDAP_TIMEOUT=5
            - LDAP_SSL=false
            - LDAP_TLS=false
        networks:
            - web
        depends_on:
            - update
            - mysql
            - redis


    web:
        image: justinlaureano/wmsa-web:latest
        command: sh -c "/var/www/html/wait-for-it.sh core:9000 -t 120 && nginx -g \"daemon off;\""
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: on-failure
        ports:
            - '80:80'
            - '443:443'
        networks:
            - web
        depends_on:
            - core
            - reverb


    mysql:
        image: justinlaureano/wmsa-mysql:latest
        deploy:
            placement:
                constraints:
                    - "node.labels.db==true"
            restart_policy:
                condition: any
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s
        volumes:
            - type: volume
              source: mysql-data
              target: /var/lib/mysql
        environment:
            - MYSQL_USER=${DB_USER}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=wms
        networks:
            - web

    redis:
        image: redis:7.4.0-alpine
        deploy:
            placement:
                constraints:
                    - "node.labels.db==true"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s
        volumes:
            - type: volume
              source: redis-data
              target: /data
        networks:
            - web


    reverb:
        image: justinlaureano/wmsa-reverb:latest
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: any
                delay: 60s
                window: 15s
        ports:
            - '8080:8080'
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_DATABASE=wms
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REVERB_APP_ID=${REVERB_APP_ID}
            - REVERB_APP_KEY=${REVERB_APP_KEY}
            - REVERB_APP_SECRET=${REVERB_APP_SECRET}
            - REVERB_HOST="web"
            - REVERB_PORT=80
            - REVERB_SCHEME=http
            - REVERB_SCALING_ENABLED=true
        networks:
            - web
        depends_on:
            - update


    scheduler:
        image: justinlaureano/wmsa-scheduler:latest
        command: sh -c "/var/www/html/wait-for-it.sh mysql:3306 -t 60 && /var/www/html/wait-for-it.sh redis:6379 -t 60 && /var/www/html/scheduler.sh"
        deploy:
            replicas: 1
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: any
                delay: 60s
                window: 15s
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_DATABASE=wms
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
        networks:
            - web
        depends_on:
            - update
            - mysql
            - redis


    worker:
        image: justinlaureano/wmsa-worker:latest
        command: sh -c "/var/www/html/wait-for-it.sh mysql:3306 -t 60 && /var/www/html/wait-for-it.sh redis:6379 -t 60 && /var/www/html/worker.sh"
        deploy:
            replicas: 2
            placement:
                constraints:
                    - "node.labels.db!=true"
            restart_policy:
                condition: any
                delay: 5s
                window: 15s
        healthcheck:
            test: [ "CMD", "php", "/var/www/html/artisan", "queue:monitor", "default" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 15s
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_DATABASE=wms
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
        networks:
            - web
        depends_on:
            - update
            - mysql
            - redis


    update:
        image: justinlaureano/wmsa-update:latest
        command: sh -c "/var/www/html/wait-for-it.sh mysql:3306 -t 60 && /var/www/html/wait-for-it.sh redis:6379 -t 60 && /var/www/html/update.sh"
        deploy:
            mode: replicated-job
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=false
            - DB_HOST=mysql
            - DB_DATABASE=wms
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - web
        depends_on:
            - mysql
            - redis


networks:
    web:
        driver: overlay
        attachable: true

volumes:
    mysql-data:
    redis-data:
